version: '3.8'

services:
  node1:
    build: .
    ports:
      - "8001:8000"
    environment:
      - NODE_ID=node1
      - HTTP_ADDR=0.0.0.0:8000
      - RAFT_ADDR=127.0.0.1:9000
      - BOOTSTRAP=true

  node2:
    build: .
    ports:
      - "8002:8000"
    environment:
      - NODE_ID=node2
      - HTTP_ADDR=0.0.0.0:8000
      - RAFT_ADDR=127.0.0.1:9000

  node3:
    build: .
    ports:
      - "8003:8000"
    environment:
      - NODE_ID=node3
      - HTTP_ADDR=0.0.0.0:8000
      - RAFT_ADDR=127.0.0.1:9000

